config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  get '/list', to: 'posts#list_by_seen'
  root 'posts#index'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :owner, class_name: 'User'
    validates :content, :seen,  presence: true
    validates :content, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    #Get /posts
    before_action :authenticate_user!
    def index
        @posts = Post.all
    end
    #Get /posts/id
    def show
        @post = Post.find(params[:id])
       ActionCable.server.broadcast('notification_channel', 'You have visited the welcome page.')
    end
    
    def new
        @post = Post.new
    end
    
    def create
        d = Date.new(params[:post]["expire(1i)"].to_i,  params[:post]["expire(2i)"].to_i,  params[:post]["expire(3i)"].to_i)
        @post = Post.new(content: params[:post][:content], 
                         seen: params[:post][:seen], 
                         expire: d)
         @post.owner_id = current_user.id

        
       if @post.seen == '0'
            @post.seen = 'No visto'
       else
           @post.seen = 'Visto'
       end
            
        if @post.save
            redirect_to @post
        else
           render :new
        end
        
        
    
    end
    
    
    def update
         d = Date.new(params[:post]["expire(1i)"].to_i,  params[:post]["expire(2i)"].to_i,  params[:post]["expire(3i)"].to_i)
         seens = ''
        if params[:post][:seen] == '0'
            seens = 'No visto'
        else
           seens = 'Visto'
        end
        @post = Post.find(params[:id])
        if @post.update(content: params[:post][:content], 
                         seen: seens, 
                         expire: d) 
            redirect_to @post
        else
            redirect_to :edit
        end
    end
    
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    
    end
    
    def edit
        @post = Post.find(params[:id])
    end
    
    def list_by_seen
        @posts = Post.all
        @posts_filter = Post.where("seen = ?", "No visto")
    
    end
    
    private
    
    def post_params
        params.require(:post).permit(:content,:seen, :expire)
    end

end 

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
    def create
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   
    <%= yield %>
    
  </body>
</html>

app/views/posts/_form.html.erb
 <div class = "form-div">
  <h1> <%= nombre %> announcement</h1>
 <%= form_for(@post) do |f| %>
 <% @post.errors.full_messages.each do |message| %>
  <div class= "be-red">
   * <%= message%>
   
  </div>
 <% end %>
 
  <%= f.label "Ride the content",:class => "field-label" %>
  <div class = "field">
     
      <%= f.text_area :content, placeholder: "Contenido", :class => "field-input" %>
  </div>
  
   <div class = "field">
      <%= f.label "Seen", :class => "field-visto" %>
      <%= f.check_box :seen, placeholder: "Seen", class:"field-check"%>
  </div>
   <%= f.label "Expiration date",:class => "field-label" %><br>
   <div class = "field">
       
      <%= f.date_select :expire, placeholder: "Seen", class:"field-input"%>
  </div>
  <br>
    <div class = "actions">
      <%= f.submit nombre, :class => "field-submit" %>
   </div>
     
 
 <% end %>
  </div>

app/views/posts/_header.html.erb
 <header class="header">
     
      <nav>
        <% if user_signed_in? %>
        <ul class="header-ul" >
            <li class= "nav-li"><%= link_to 'Create',new_post_url , :method => :get, :class => "clases" %></li>
            <li class= "nav-li"><%= link_to 'Filter ',list_path,:method => :get, :class => "clases" %></li>  
            <li class= "nav-li"><%= link_to 'All announcements ',posts_path,:method => :get, :class => "clases" %></li>  
            <li class= "nav-li"><%= link_to 'Sign off ',destroy_user_session_path,:method => :delete, :class => "clases" %></li> 
            
        </ul>
        <%else%>
        <ul class="header-ul">
            <li class= "nav-li"><%= link_to 'Login',new_user_session_path,:method => :get, :class => "clases" %></li>  
            <li class= "nav-li"><%= link_to 'Sign up',new_user_registration_path,:method => :get, :class => "clases" %></li>  
        </ul>
        <%end %>
    </nav>
  </header>

app/views/posts/edit.html.erb
 <%= render "header" %>
<%= render "form", nombre: "Edit" %>

app/views/posts/index.html.erb
<%= render "header" %>
<div class= "div-table-announcements">
 <h2>All announcements</h2>
<table class= "table">
    <thead>
        <tr>
            <th>Content</th>
            <th>expire</th>
            <th>seen</th>
            <th>Created by</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
  

<% @posts.each do |poster| %>
    <tbody>
     <tr>
        <td><%= link_to poster.content, poster %></td>
        <td><%= poster.expire %></td>
        <td><%= poster.seen %></td>
        <td><%= User.find(poster.owner_id).email %></td>
        <td><%= link_to "Delete", poster , method: :delete ,data: {confirm: "Are you sure?"} %> </td>
        <td><%= link_to "Edit", edit_post_path(poster) %> </td>
    </tr> 
    </tbody>
  
<% end %>
</table>
</div>

app/views/posts/list_by_seen.html.erb
 <%= render "header" %>
 <div class= "div-table-announcements">
<h1> Not seen announcements</h1>

<table class= "table">
    <thead>
    <tr>
        <th>Content</th>
        <th>expire</th>
        <th>seen</th>
        <th>Created by</th>
    </tr>
    </thead>

<% @posts_filter.each do |post| %>
    <tbody>
    <tr>
        <td><%= post.content %></td>
        <td><%= post.expire %></td>
        <td><%= post.seen %></td>
        <td><%= User.find(post.owner_id).email %></td>
    </tr>
    </tbody>

<% end %>
</table>
</div>

app/views/posts/new.html.erb
 <%= render "header" %>

<%= render "form", nombre: "Create" %>

app/views/posts/show.html.erb
<%= render "header" %>
<header>
    <div class="form-div-h1">
        <h1>Your announcement was created successfully</h1>
     </div>
     <% (1..10).each do |f| %>
         <br>
     <% end %>
 
    <div class="form-div">
    <h4><%='Content: '+ @post.content %></h4>

    <h4><%= 'Seen:    '+@post.seen %></h4>

    <h4><%= 'Expiration date:    '+ @post.expire.to_s %></h4>

    <%= link_to 'Send Notification',remote: true %>
    
    </div>
    
</header>

app/views/posts/show.js.erb
if (Notification.permission === 'granted') {
  var title = 'Hogaru Notification'
  var body = 'Someone created a new announcement'
  var options = { body: body }
  new Notification(title, options)
}

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>